# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8913d78aa5b0e4bd28a04ffa27ce99fbac745631595debd6290bd0b7e54c50646047b956832397a70cc13e4bb3cb48ff47d87ae4ca4719463d5a2fe00a141cd

test:
  secret_key_base: c7e8703f925ea6b405d4c4973b55cad4d2c9d164cc31f0e8c277981c0158ab5dfbb495eafd7cfb988e5fc8c6c3100fea8a31a68998ed4f09fc8bf221c70dfd68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
